import { NextResponse } from 'next/server'
import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'
import { createAdminClient } from '@/lib/supabase-admin'
import { fetchAdmin, fetchSchoolClasses, fetchSchoolTeachers } from '@/lib/admin-queries'

type Row = Record<string, unknown>

async function auth(userId: string, schoolId: string) {
  const ac = createAdminClient()
  const admin = await fetchAdmin(userId, ac)
  if (!admin || admin.schoolId !== schoolId) return null
  return { admin, ac }
}

function sb(cookieStore: ReturnType<typeof cookies>) {
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { cookies: { getAll: () => cookieStore.getAll(), setAll: (cs) => cs.forEach(({ name, value, options }) => cookieStore.set(name, value, options)) } }
  )
}

// ── GET — every Prep Material generated by any teacher in this school, for admin browsing ──
export async function GET(_req: Request, { params }: { params: { schoolId: string } }) {
  try {
    const cookieStore = cookies()
    const { data: { user } } = await sb(cookieStore).auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const ctx = await auth(user.id, params.schoolId)
    if (!ctx) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

    const [classes, teachers] = await Promise.all([
      fetchSchoolClasses(params.schoolId, ctx.ac),
      fetchSchoolTeachers(params.schoolId, ctx.ac),
    ])
    const classIds = classes.map(c => c.id)
    if (classIds.length === 0) return NextResponse.json({ materials: [] })

    const { data, error } = await ctx.ac
      .from('prep_materials')
      .select('*')
      .in('class_id', classIds)
      .order('created_at', { ascending: false })
    if (error) return NextResponse.json({ error: error.message }, { status: 500 })

    // Session count per class+topic — how many times this was actually taught in class,
    // not just generated. Matched the same way the rest of the app matches topic strings:
    // trimmed, case-insensitive, keyed by class_id since topic names aren't globally unique.
    const { data: sessionRows } = await ctx.ac
      .from('sessions')
      .select('class_id, topic')
      .in('class_id', classIds)
    const sessionCounts = new Map<string, number>()
    for (const s of (sessionRows ?? []) as Row[]) {
      const key = `${s.class_id}|${(s.topic as string).trim().toLowerCase()}`
      sessionCounts.set(key, (sessionCounts.get(key) ?? 0) + 1)
    }

    const classById   = new Map(classes.map(c => [c.id, c]))
    const teacherById = new Map(teachers.map(t => [t.id, t]))

    const materials = ((data ?? []) as Row[]).map(r => {
      const cls = classById.get(r.class_id as string)
      const teacher = teacherById.get(r.teacher_id as string)
      const sessionKey = `${r.class_id}|${(r.topic as string).trim().toLowerCase()}`
      return {
        id: r.id as string,
        teacherName: teacher?.name ?? 'Unknown teacher',
        className: cls?.name ?? 'Unknown class',
        grade: (r.grade as string) ?? cls?.grade ?? '',
        subject: (r.subject as string) ?? '',
        topic: r.topic as string,
        subtopic: (r.subtopic as string) ?? undefined,
        createdAt: r.created_at as string,
        sessionCount: sessionCounts.get(sessionKey) ?? 0,
        lesson: r.lesson,
      }
    })

    return NextResponse.json({ materials })
  } catch (err) {
    console.error('[admin prep-materials GET] failed:', err)
    return NextResponse.json({ error: 'Server error' }, { status: 500 })
  }
}
